version: '2.3'

services:
    prisma:
        image: prismagraphql/prisma:1.34
        restart: always
        ports:
            - 4466:4466
        links:
            - postgres
        environment:
            PRISMA_CONFIG: |
                port: 4466
                managementApiSecret: mysecret42
                databases:
                  default:
                    connector: postgres
                    host: postgres
                    port: 5432
                    user: postgres
                    password: postgres
        healthcheck:
            test: wget -q --spider http://localhost:4466/management || exit 1

    postgres:
        image: postgres:10.3
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        healthcheck:
            test: psql --username=postgres --dbname=postgres --command=SELECT * FROM pg_catalog.pg_tables;
